### ISSUE TITLE
TODO: 주말에 할 것들!!

### ISSUE THREAD

**Issue by eun-seong** [woowa-techcamp-2021/deal-5#41]
- [x] 글쓰기 페이지
- [x] 채팅 제대로 동작하게 하기
    - [x] 스크롤이 채팅방 안에서만 생기면 좋겠다.
    - [x] 채팅 입력창이 줄 수에 맞춰 커지고 작아지고
    - [x] 2.5줄 이상되면 스크롤로 하면 좋겠다.
    - [x] 메세지 보내기 버튼 활성화
- [ ] 라우터...
- [ ] 실시간 채팅...(추후에..)
