### ISSUE TITLE
TODO : 주말 계획

### ISSUE THREAD

**Issue by HanCheo** [woowa-techcamp-2021/deal-5#42]
- 메인페이지
 - [x] 상품목록 드롭다운
 - [x] 북마크 기능 안되는거 수정
 - [x] 상품 페이지 이동 추가
 - [x]  사이드바 백그라운드 클릭시 class 토글
 -  상품상세 페이지
 - [x] 슬라이드 : 슬랙 url 확인
 - [x] 드롭다운, 셀렉트 박스
 - [x] 상품 주인 / 아닐 경우 ui 변경
 - [x] 셀렉트박스 옵션 ui
 - [x] 북마크 기능
 - [x] 채팅 하기 / 목록 보기 페이지 전환
 - 서버 관련 생각
 - [x] 실시간 채팅 : 은성님 화이팅

**Comment by eun-seong** [comment]
ㅋㅋㅋㅋ화이팅,,,
